runtime: python39  # Choose the appropriate runtime version
entrypoint: gunicorn -b :$PORT app:app  # Replace 'your_app' with your Flask app's main file

env_variables:
  FLASK_ENV: production  # Set the Flask environment to 'production'

automatic_scaling:
  target_cpu_utilization: 0.65  # Adjust this setting based on your application's needs
